#ifndef BSP_CONFIG_STM32F103_H
#define BSP_CONFIG_STM32F103_H

#if (BSP_BUZZER_HW_CONFIG_ENABLE == 1U)
#define BSP_BUZZER_GPIO_PORT            GPIOA
#define BSP_BUZZER_PIN                  GPIO_PIN_8
#define BSP_BUZZER_GPIO_CLK_ENABLE()    __HAL_RCC_GPIOA_CLK_ENABLE()
#endif

#if (BSP_RELAY_HW_CONFIG_ENABLE == 1U)
#define BSP_RELAY_GPIO_PORT             GPIOD
#define BSP_RELAY_PIN                   GPIO_PIN_2
#define BSP_RELAY_GPIO_CLK_ENABLE()     __HAL_RCC_GPIOD_CLK_ENABLE()
#endif

#if (BSP_KEY_HW_CONFIG_ENABLE == 1U)
#define BSP_KEY_GPIO_PORT               GPIOA
#define BSP_KEY_PIN_SET                 GPIO_PIN_13
#define BSP_KEY_PIN_UP                  GPIO_PIN_0
#define BSP_KEY_PIN_DOWN                GPIO_PIN_15
#define BSP_KEY_GPIO_CLK_ENABLE()       __HAL_RCC_GPIOA_CLK_ENABLE()
#define BSP_KEY_AFIO_CLK_ENABLE()       __HAL_RCC_AFIO_CLK_ENABLE()
#define BSP_KEY_SWJ_REMAP()             __HAL_AFIO_REMAP_SWJ_DISABLE()
#define BSP_KEY_UP_ACTIVE_HIGH          (1U)
#endif

#if (BSP_UART_HW_CONFIG_ENABLE == 1U)
#define BSP_UART_BAUDRATE             (115200U)
#define BSP_UART_GPIO_PORT              GPIOA
#define BSP_UART_PIN_TX                 GPIO_PIN_9
#define BSP_UART_PIN_RX                 GPIO_PIN_10
#define BSP_UART_GPIO_CLK_ENABLE()      __HAL_RCC_GPIOA_CLK_ENABLE()
#define BSP_UART_PERIPH_CLK_ENABLE()    __HAL_RCC_USART1_CLK_ENABLE()
#else
#define BSP_UART_BAUDRATE               (115200U)
#endif

#if (BSP_EEPROM_HW_CONFIG_ENABLE == 1U)
#define BSP_EEPROM_I2C_ADDR_7BIT      (0x50U)
#define BSP_EEPROM_I2C_SPEED_HZ       (100000U)
#define BSP_EEPROM_TOTAL_SIZE_BYTES   (256U)
#define BSP_EEPROM_PAGE_SIZE_BYTES    (8U)
#define BSP_EEPROM_GPIO_PORT            GPIOB
#define BSP_EEPROM_PIN_SCL              GPIO_PIN_10
#define BSP_EEPROM_PIN_SDA              GPIO_PIN_11
#define BSP_EEPROM_GPIO_CLK_ENABLE()    __HAL_RCC_GPIOB_CLK_ENABLE()
#define BSP_EEPROM_PERIPH_CLK_ENABLE()  __HAL_RCC_I2C2_CLK_ENABLE()
#else
#define BSP_EEPROM_I2C_ADDR_7BIT        (0x50U)
#define BSP_EEPROM_I2C_SPEED_HZ         (100000U)
#define BSP_EEPROM_TOTAL_SIZE_BYTES     (256U)
#define BSP_EEPROM_PAGE_SIZE_BYTES      (8U)
#endif

#if (BSP_SPIFLASH_HW_CONFIG_ENABLE == 1U)
#define BSP_SPIFLASH_TOTAL_SIZE_BYTES (8U * 1024U * 1024U)
#define BSP_SPIFLASH_GPIO_PORT          GPIOA
#define BSP_SPIFLASH_PIN_SCK            GPIO_PIN_5
#define BSP_SPIFLASH_PIN_MISO           GPIO_PIN_6
#define BSP_SPIFLASH_PIN_MOSI           GPIO_PIN_7
#define BSP_SPIFLASH_PIN_CS             GPIO_PIN_2
#define BSP_SPIFLASH_GPIO_CLK_ENABLE()  __HAL_RCC_GPIOA_CLK_ENABLE()
#define BSP_SPIFLASH_PERIPH_CLK_ENABLE() __HAL_RCC_SPI1_CLK_ENABLE()
#else
#define BSP_SPIFLASH_TOTAL_SIZE_BYTES   (8U * 1024U * 1024U)
#endif

#define BSP_SENSOR_DS18B20_SENSOR_COUNT  (3U)

#if (BSP_SENSOR_DS18B20_HW_CONFIG_ENABLE == 1U)
#define BSP_SENSOR_DS18B20_GPIO_APB2_MASK RCC_APB2Periph_GPIOA
#define BSP_SENSOR_DS18B20_GPIO_PORT_0   GPIOA
#define BSP_SENSOR_DS18B20_GPIO_PORT_1   GPIOA
#define BSP_SENSOR_DS18B20_GPIO_PORT_2   GPIOA
#define BSP_SENSOR_DS18B20_PIN_0         GPIO_PIN_1
#define BSP_SENSOR_DS18B20_PIN_1         GPIO_PIN_3
#define BSP_SENSOR_DS18B20_PIN_2         GPIO_PIN_4
#define BSP_SENSOR_DS18B20_PIN_SOURCE_0  GPIO_PinSource1
#define BSP_SENSOR_DS18B20_PIN_SOURCE_1  GPIO_PinSource3
#define BSP_SENSOR_DS18B20_PIN_SOURCE_2  GPIO_PinSource4
#endif

#endif
