[platformio]
default_envs = temperatureSensor-Debug
src_dir = firmware

[env]
platform = ststm32
framework = stm32cube
extra_scripts = pre:firmware/platformio/hal/pio_progname.py
upload_protocol = stlink
monitor_speed = 115200
build_src_filter =
  +<Core/Src/*.c>
  +<Drivers/BSP/bsp_buzzer.c>
  +<Drivers/BSP/bsp_ds18b20.c>
  +<Drivers/BSP/bsp_eeprom.c>
  +<Drivers/BSP/bsp_key.c>
  +<Drivers/BSP/bsp_oled.c>
  +<Drivers/BSP/bsp_relay.c>
  +<Drivers/BSP/bsp_rtc.c>
  +<Drivers/BSP/bsp_spiflash.c>
  +<Drivers/BSP/bsp_uart.c>
  +<Drivers/BSP/tiny_graphics.c>
  +<ThirdParty/lvgl/src/lv_init.c>
  +<ThirdParty/lvgl/src/core/*.c>
  +<ThirdParty/lvgl/src/display/*.c>
  +<ThirdParty/lvgl/src/draw/*.c>
  +<ThirdParty/lvgl/src/draw/convert/*.c>
  +<ThirdParty/lvgl/src/draw/sw/*.c>
  +<ThirdParty/lvgl/src/draw/sw/blend/*.c>
  +<ThirdParty/lvgl/src/font/lv_font.c>
  +<ThirdParty/lvgl/src/font/lv_font_montserrat_14.c>
  +<ThirdParty/lvgl/src/font/lv_font_montserrat_20.c>
  +<ThirdParty/lvgl/src/font/fmt_txt/*.c>
  +<ThirdParty/lvgl/src/indev/lv_gridnav.c>
  +<ThirdParty/lvgl/src/indev/lv_indev.c>
  +<ThirdParty/lvgl/src/indev/lv_indev_gesture.c>
  +<ThirdParty/lvgl/src/indev/lv_indev_scroll.c>
  +<ThirdParty/lvgl/src/layouts/*.c>
  +<ThirdParty/lvgl/src/layouts/flex/*.c>
  +<ThirdParty/lvgl/src/layouts/grid/*.c>
  +<ThirdParty/lvgl/src/misc/*.c>
  +<ThirdParty/lvgl/src/misc/cache/*.c>
  +<ThirdParty/lvgl/src/misc/cache/class/lv_cache_lru_rb.c>
  +<ThirdParty/lvgl/src/misc/cache/instance/*.c>
  +<ThirdParty/lvgl/src/osal/lv_os.c>
  +<ThirdParty/lvgl/src/osal/lv_os_none.c>
  +<ThirdParty/lvgl/src/stdlib/lv_mem.c>
  +<ThirdParty/lvgl/src/stdlib/builtin/*.c>
  +<ThirdParty/lvgl/src/stdlib/clib/*.c>
  +<ThirdParty/lvgl/src/themes/*.c>
  +<ThirdParty/lvgl/src/themes/simple/*.c>
  +<ThirdParty/lvgl/src/themes/mono/*.c>
  +<ThirdParty/lvgl/src/tick/*.c>
  +<ThirdParty/lvgl/src/widgets/button/*.c>
  +<ThirdParty/lvgl/src/widgets/label/*.c>
  +<ThirdParty/lvgl/src/libs/bin_decoder/lv_bin_decoder.c>

[env:chip-stm32f103]
extends = env
board = genericSTM32F103RB
build_flags =
  -Ifirmware/Core/Inc
  -Ifirmware/Drivers/BSP
  -Ifirmware/ThirdParty/lvgl
  -D USE_HAL_DRIVER
  -D STM32F103xB
  -D APP_CHIP_STM32F103=1

[env:chip-stm32f407vgt6]
extends = env
board = genericSTM32F407VGT6
build_flags =
  -Ifirmware/Core/Inc
  -Ifirmware/Drivers/BSP
  -Ifirmware/ThirdParty/lvgl
  -Ifirmware/platformio/hal/include_f4compat
  -D USE_HAL_DRIVER
  -D STM32F407xx
  -D APP_CHIP_STM32F407VGT6=1

[env:temperatureSensor-Debug]
extends = chip-stm32f103
board = genericSTM32F103RB
build_type = debug
build_flags =
  ${env:chip-stm32f103.build_flags}
  -D APP_PROJECT_STM32F103=1
  -D APP_BUILD_DEBUG=1
  -D APP_HW_DRIVER_TEST_DISPLAY=1

[env:temperatureSensor-Release]
extends = chip-stm32f103
board = genericSTM32F103RB
build_type = release
build_flags =
  ${env:chip-stm32f103.build_flags}
  -D APP_PROJECT_STM32F103=1
  -D APP_BUILD_RELEASE=1

[env:edgegateway-Debug]
extends = chip-stm32f407vgt6
board = genericSTM32F407VGT6
build_type = debug
build_flags =
  ${env:chip-stm32f407vgt6.build_flags}
  -D APP_PROJECT_EDGEGATEWAY=1
  -D APP_BUILD_DEBUG=1
  -D APP_HW_DRIVER_TEST_DISPLAY=1

[env:edgegateway-Release]
extends = chip-stm32f407vgt6
board = genericSTM32F407VGT6
build_type = release
build_flags =
  ${env:chip-stm32f407vgt6.build_flags}
  -D APP_PROJECT_EDGEGATEWAY=1
  -D APP_BUILD_RELEASE=1

[env:edgegateway_hal]
extends = edgegateway-Release

[env:stm32f103rb_hal]
extends = temperatureSensor-Release

[env:Release]
extends = temperatureSensor-Release
